#!/usr/bin/env node
// Husky commit-msg hook: enforces Conventional Commits, no dependencies.
//
// Usage (installed by apply-quality.sh as .husky/commit-msg):
//   node scripts/quality/commit-msg.mjs "$1"
//
// $1 is the path to the file git wrote the commit message into.
//
// Rules:
//   - header line matches: type(scope)?: subject
//   - type is one of the allowed set below
//   - subject is 1..100 characters (after "type(scope): ")
//   - merge commits ("Merge ...") are always allowed
//   - trailer lines (e.g. "Co-Authored-By: ...") are ignored, not validated
//     as the header
//
// Exit codes: 0 = accepted, 1 = rejected (message printed to stderr).

import { readFileSync } from 'node:fs';

const TYPES = [
  'feat',
  'fix',
  'chore',
  'docs',
  'test',
  'refactor',
  'perf',
  'build',
  'ci',
  'revert',
  'spike',
];

const HEADER_RE = new RegExp(`^(${TYPES.join('|')})(\\([^)]+\\))?: (.{1,100})$`);

function firstMeaningfulLine(message) {
  const lines = message.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;
    // Skip comment lines git leaves in (from `git commit -v` / templates).
    if (trimmed.startsWith('#')) continue;
    return trimmed;
  }
  return '';
}

function main(argv) {
  const messageFile = argv[2];
  if (!messageFile) {
    // No file to check: fail open rather than block every commit on a
    // misconfigured hook invocation.
    return 0;
  }

  let raw;
  try {
    raw = readFileSync(messageFile, 'utf8');
  } catch {
    return 0;
  }

  const header = firstMeaningfulLine(raw);
  if (header.length === 0) {
    process.stderr.write('commit-msg: empty commit message.\n');
    return 1;
  }

  // Merge commits are exempt: their header is generated by git, not authored.
  if (/^Merge /.test(header)) return 0;

  // A commit whose only content beyond trailers is a Co-Authored-By line is
  // still validated on its own header; the trailer itself is never the thing
  // matched against HEADER_RE because firstMeaningfulLine stops at the first
  // non-empty, non-comment line, which is always the subject line.

  if (HEADER_RE.test(header)) return 0;

  process.stderr.write(
    'commit-msg: message must match "type(scope)?: subject" ' +
      `(type: ${TYPES.join('|')}; subject 1-100 chars).\n` +
      `  example: feat(auth): add password reset flow\n` +
      `  got: ${header}\n`,
  );
  return 1;
}

process.exit(main(process.argv));
